//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteProfss_v01.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public int Id { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Parametro { get; set; }
        public bool Activa { get; set; }
        public int SolicitanteId { get; set; }
        public int CategoriaId { get; set; }
        public int DepartamentoId { get; set; }
    
        public virtual Solicitante Solicitante { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Departamento Departamento { get; set; }
    }
}
