//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteProfss_v01.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AptitudRequerida
    {
        public int Id { get; set; }
        public int OfertaId { get; set; }
        public int AptitudId { get; set; }
        public int NivelId { get; set; }
        public int OfertaId1 { get; set; }
    
        public virtual Aptitud Aptitud { get; set; }
        public virtual Nivel Nivel { get; set; }
        public virtual Oferta Oferta { get; set; }
    }
}
