//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteProfss_v01.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaCategoria
    {
        public int Id { get; set; }
        public int EmpresaId { get; set; }
        public int CategoriaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
