//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteProfss_v01.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oferta()
        {
            this.Visitas = new HashSet<Visita>();
            this.Solicitudes = new HashSet<Solicitud>();
            this.AptitudesRequeridas = new HashSet<AptitudRequerida>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public string AreaLaboral { get; set; }
        public int CantidadVacantes { get; set; }
        public string HabilidadesRequeridas { get; set; }
        public int EdadDesde { get; set; }
        public int EdadHasta { get; set; }
        public bool Remuneracion { get; set; }
        public bool TransporteRecorrido { get; set; }
        public System.DateTime FechaLimiteSolicitud { get; set; }
        public bool Anulada { get; set; }
        public int EmpresaId { get; set; }
        public int CategoriaId { get; set; }
        public int DepartamentoId { get; set; }
        public int TiempoContratacionId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visita> Visitas { get; set; }
        public virtual TiempoContratacion TiempoContratacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AptitudRequerida> AptitudesRequeridas { get; set; }
    }
}
