//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteProfss_v01.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int Id { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string ComentariosSolicitante { get; set; }
        public string ComentariosEmpresa { get; set; }
        public bool VistaEmpresa { get; set; }
        public Nullable<System.DateTime> FechaVista { get; set; }
        public int SolicitanteId { get; set; }
        public int OfertaId { get; set; }
    
        public virtual Solicitante Solicitante { get; set; }
        public virtual Oferta Oferta { get; set; }
    }
}
