//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteProfss_v01.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitante : Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitante()
        {
            this.Solicitudes = new HashSet<Solicitud>();
            this.SolicitanteAptitudes = new HashSet<SolicitanteAptitud>();
            this.Alertas = new HashSet<Alerta>();
        }
    
        public string NumeroCarnet { get; set; }
        public string NumeroCedula { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public string Descripcion { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoCelular1 { get; set; }
        public string TelefonoCelular2 { get; set; }
        public byte[] CurriculumVitae { get; set; }
        public Nullable<int> CarreraId { get; set; }
        public int SexoId { get; set; }
        public int AnioAcademicoId { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual AnioAcademico AnioAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitanteAptitud> SolicitanteAptitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerta> Alertas { get; set; }
    }
}
