//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteProfss_v01.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] Foto { get; set; }
        public string Direccion { get; set; }
        public string SitioWeb { get; set; }
        public string DireccionFacebook { get; set; }
        public Nullable<int> MunicipioId { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
